# Pixels and Colors
Let's first look at the numerical representation and storage of an image.<br>
Pixels, also referred to as picture elements, are the smallest unit of an image. Essentially, it's just a dot in the image.<br>Numerous pixels are grouped in **rows and columns** within an image. The number of rows and columns is frequently stated as the image **resolution**.<br>An Ultra HD TV, for instance, measures 3840 pixels wide by 2160 pixels high, or 3840x2160 pixels.<br>Each pixel has a particular color. But they are not recognized as color dots by a computer.<br> A computer can only understand numerical data.<br>
![example_of_pixels_in_image](imgs/pixels_example.jpg)


## Black and White Images
Each pixel in a grayscale (black and white) image is a **single number that indicates the intensity —or amount— of light** that it contains.<br>The range of intensities in many applications is 0 (black) to 255 (white).<br>Grayscale is present in all values between 0 and 255.<br>
![example_of_pixels_intensity_in_grayscale_image](imgs/grayscale_image_intensity.png)


In the following lines of code, we will use python to **read a black and white image** and see **how it is represented on a computer**.


In [1]:
from PIL import Image
import numpy as np

# Specify the path to our black and white image
image_path = 'imgs/kitten-black-white.jpg'

# Open the image (color: rbg)
image = Image.open(image_path)
# Convert the RGB image to grayscale
gray_image = image.convert('L')

# Convert the image to a NumPy array
image_array = np.array(gray_image)

# Print the NumPy array and display basic information about the image
print(f"The array of the image:\n {image_array}")
print(f"Image format: {gray_image.format}")
print(f"Image mode: {gray_image.mode}")
print(f"Image size: {gray_image.size}")

# Show the image
image.show()


The array of the image:
 [[ 7  7  7 ... 28 27 27]
 [ 7  7  7 ... 28 28 27]
 [ 7  7  7 ... 28 28 28]
 ...
 [ 0  0  0 ...  3  3  3]
 [ 0  0  0 ...  3  3  3]
 [ 0  0  0 ...  4  4  4]]
Image format: None
Image mode: L
Image size: (728, 729)


Breakdown of the code:
- Image.open(image_path): Opens the image file specified by image_path.
- rgb_image.convert('L'): Converts the RGB image to grayscale.
- np.array(image): Converts the image to a NumPy array. For a black and white image, each element of the array will represent the intensity of a pixel.
- print(image_array): print the array directly. Might not be practical for large images, but it will show you the numerical representation of the pixel values.
- image.format: Returns the file format of the image (e.g., JPEG, PNG)
- image.mode: Returns the color mode of the image (e.g., 'L' for grayscale, 'RGB' for color).
- image.size: Returns a tuple representing the width and height of the image in pixels.
- image.show(): Opens the default image viewer to display the image.


So, let's say we want to see the **intensity value** contained in the pixel located in the **101st row and 150th column**.


In [2]:
# Specify the coordinates of the pixel you want to check
row_index = 100  # Note: Python uses 0-based indexing, so 100 corresponds to the 101st row
col_index = 149  # Note: Python uses 0-based indexing, so 149 corresponds to the 150th column

# Get the intensity value of the specified pixel
pixel_intensity = image_array[row_index, col_index]

# Print the intensity value
print(f"The intensity value of the pixel at row {row_index + 1} and column {col_index + 1} is: {pixel_intensity}")


The intensity value of the pixel at row 101 and column 150 is: 42


This code retrieves the intensity value of the pixel at the specified row and column in the gray image_array NumPy array.<br>Note that the row and column indices are adjusted by 1 because Python uses 0-based indexing.
